alert("heli the queen");
document.write("heli the queen"); 
var name = "david";
document.write("hello" + "name");
var name = prompt("Enter your name:", "");
document.write("hello " + "name");
var age = prompt("Enter your age:", 0);
document.write("age next yeat is " + "age"+1 );
var num1 = parseInt(prompt("Enter first number: "));
var num2 = parseInt(prompt("Enter second number: "));
document.write("</br>");
document.write((num1 + num2));
document.write("</br>");
document.write(num1 - num2);
document.write("</br>");
document.write(num1 * num2);
document.write("</br>");
document.write(num1 / num2);